[template]
include = ["Cargo.toml", "Cargo.lock", ".github/workflows/*", "*.rs"]

[placeholders.itch_username]
prompt = "Enter your itch.io username. Leave blank to disable itch.io upload."
type = "string"
default = ""
