[build]
# Point to our subdirectory
target = "web/index.html"
# This is needed in order to host the game on itch.io
public_url = "./"

[server]
# Required for asset loading
no_spa = true
# Open a browser tab once the initial build is complete.
open = true
