name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run cargo test --all-targets
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache target directory
        uses: Leafwing-Studios/cargo-cache@v1

      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

      - name: Run cargo test
        run: cargo test --all-targets

  # Run cargo clippy --all-targets -- -D warnings --all-targets
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache target directory
        uses: Leafwing-Studios/cargo-cache@v1

      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache target directory
        uses: Leafwing-Studios/cargo-cache@v1

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

# Run cargo doc --no-deps
  doc:
    name: Doc
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache target directory
        uses: Leafwing-Studios/cargo-cache@v1

      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

      - name: Run cargo doc
        run: cargo doc --no-deps
